//! Side effects generated by the reducer.

use crate::Job;
use std::path::PathBuf;

/// Effects represent side effects that should be executed after state updates.
#[derive(Debug, Clone)]
pub enum Effect {
    /// No effect.
    None,

    /// Open a repository.
    OpenRepo(PathBuf),

    /// Refresh the current repository.
    RefreshRepo(PathBuf),

    /// Save configuration to disk.
    SaveConfig,

    /// Execute multiple effects in sequence.
    Batch(Vec<Effect>),

    /// Load commit history for a repository.
    LoadCommitHistory(PathBuf),

    /// Load diff for a specific commit.
    LoadCommitDiff {
        repo_path: PathBuf,
        commit_hash: String,
    },

    /// Load working directory status.
    LoadWorkingDirStatus(PathBuf),

    /// Stage a file.
    StageFile {
        repo_path: PathBuf,
        file_path: PathBuf,
    },

    /// Stage multiple files.
    StageFiles {
        repo_path: PathBuf,
        file_paths: Vec<PathBuf>,
    },

    /// Unstage a file.
    UnstageFile {
        repo_path: PathBuf,
        file_path: PathBuf,
    },

    /// Unstage multiple files.
    UnstageFiles {
        repo_path: PathBuf,
        file_paths: Vec<PathBuf>,
    },

    /// Stage all changes.
    StageAll(PathBuf),

    /// Unstage all changes.
    UnstageAll(PathBuf),

    /// Create a commit.
    CreateCommit {
        repo_path: PathBuf,
        message: String,
        amend: bool,
        push: bool,
    },

    /// Load author identity.
    LoadAuthorIdentity(PathBuf),

    // ===== 4-Pane Layout Effects =====
    /// Load branch tree.
    LoadBranchTree(PathBuf),

    /// Checkout a branch.
    CheckoutBranch {
        repo_path: PathBuf,
        branch_name: String,
    },

    /// Check if repository has uncommitted changes.
    CheckUncommittedChanges {
        repo_path: PathBuf,
        branch_name: String,
        is_remote: bool,
    },

    /// Stash changes and checkout branch.
    StashAndCheckout {
        repo_path: PathBuf,
        branch_name: String,
        is_remote: bool,
        from_branch: String,
    },

    /// Discard changes and checkout branch.
    DiscardAndCheckout {
        repo_path: PathBuf,
        branch_name: String,
        is_remote: bool,
    },

    /// Check if local branch name exists (for remote branch checkout).
    CheckLocalBranchExists {
        repo_path: PathBuf,
        remote_branch: String,
        local_name: String,
    },

    /// Checkout remote branch (create local tracking branch).
    CheckoutRemoteBranch {
        repo_path: PathBuf,
        remote_branch: String,
        local_name: String,
        override_existing: bool,
    },

    /// Load changed files.
    LoadChangedFiles(PathBuf),

    /// Load file content.
    LoadFileContent {
        repo_path: PathBuf,
        file_path: PathBuf,
    },

    /// Load file diff.
    LoadFileDiff {
        repo_path: PathBuf,
        file_path: PathBuf,
    },

    /// Load multiple file diffs.
    LoadMultipleFileDiffs {
        repo_path: PathBuf,
        file_paths: Vec<PathBuf>,
    },

    /// Revert a file to HEAD state.
    RevertFile {
        repo_path: PathBuf,
        file_path: PathBuf,
    },

    /// Open a file in the system's default editor.
    OpenInEditor { full_path: PathBuf },

    /// Open the folder containing a file in the system's file manager.
    OpenFolder { full_path: PathBuf },
}

impl Effect {
    /// Convert effect into a background job when applicable.
    pub fn try_into_job(self) -> Result<Job, Self> {
        match self {
            Effect::OpenRepo(path) => Ok(Job::OpenRepo(path)),
            Effect::RefreshRepo(path) => Ok(Job::RefreshRepo(path)),
            Effect::LoadCommitHistory(path) => Ok(Job::LoadCommitHistory(path)),
            Effect::LoadCommitDiff {
                repo_path,
                commit_hash,
            } => Ok(Job::LoadCommitDiff {
                repo_path,
                commit_hash,
            }),
            Effect::LoadWorkingDirStatus(path) => Ok(Job::LoadWorkingDirStatus(path)),
            Effect::StageFile {
                repo_path,
                file_path,
            } => Ok(Job::StageFile {
                repo_path,
                file_path,
            }),
            Effect::StageFiles {
                repo_path,
                file_paths,
            } => Ok(Job::StageFiles {
                repo_path,
                file_paths,
            }),
            Effect::UnstageFile {
                repo_path,
                file_path,
            } => Ok(Job::UnstageFile {
                repo_path,
                file_path,
            }),
            Effect::UnstageFiles {
                repo_path,
                file_paths,
            } => Ok(Job::UnstageFiles {
                repo_path,
                file_paths,
            }),
            Effect::StageAll(path) => Ok(Job::StageAll(path)),
            Effect::UnstageAll(path) => Ok(Job::UnstageAll(path)),
            Effect::CreateCommit {
                repo_path,
                message,
                amend,
                push,
            } => Ok(Job::CreateCommit {
                repo_path,
                message,
                amend,
                push,
            }),
            Effect::LoadAuthorIdentity(path) => Ok(Job::LoadAuthorIdentity(path)),
            Effect::LoadBranchTree(path) => Ok(Job::LoadBranchTree(path)),
            Effect::CheckoutBranch {
                repo_path,
                branch_name,
            } => Ok(Job::CheckoutBranch {
                repo_path,
                branch_name,
            }),
            Effect::CheckUncommittedChanges {
                repo_path,
                branch_name,
                is_remote,
            } => Ok(Job::CheckUncommittedChanges {
                repo_path,
                branch_name,
                is_remote,
            }),
            Effect::StashAndCheckout {
                repo_path,
                branch_name,
                is_remote,
                from_branch,
            } => Ok(Job::StashAndCheckout {
                repo_path,
                branch_name,
                is_remote,
                from_branch,
            }),
            Effect::DiscardAndCheckout {
                repo_path,
                branch_name,
                is_remote,
            } => Ok(Job::DiscardAndCheckout {
                repo_path,
                branch_name,
                is_remote,
            }),
            Effect::CheckLocalBranchExists {
                repo_path,
                remote_branch,
                local_name,
            } => Ok(Job::CheckLocalBranchExists {
                repo_path,
                remote_branch,
                local_name,
            }),
            Effect::CheckoutRemoteBranch {
                repo_path,
                remote_branch,
                local_name,
                override_existing,
            } => Ok(Job::CheckoutRemoteBranch {
                repo_path,
                remote_branch,
                local_name,
                override_existing,
            }),
            Effect::LoadChangedFiles(path) => Ok(Job::LoadChangedFiles(path)),
            Effect::LoadFileContent {
                repo_path,
                file_path,
            } => Ok(Job::LoadFileContent {
                repo_path,
                file_path,
            }),
            Effect::LoadFileDiff {
                repo_path,
                file_path,
            } => Ok(Job::LoadFileDiff {
                repo_path,
                file_path,
            }),
            Effect::LoadMultipleFileDiffs {
                repo_path,
                file_paths,
            } => Ok(Job::LoadMultipleFileDiffs {
                repo_path,
                file_paths,
            }),
            Effect::RevertFile {
                repo_path,
                file_path,
            } => Ok(Job::RevertFile {
                repo_path,
                file_path,
            }),
            other => Err(other),
        }
    }
}
