//! Side effects generated by the reducer.

use std::path::PathBuf;

/// Effects represent side effects that should be executed after state updates.
#[derive(Debug, Clone)]
pub enum Effect {
    /// No effect.
    None,

    /// Open a repository.
    OpenRepo(PathBuf),

    /// Refresh the current repository.
    RefreshRepo(PathBuf),

    /// Save configuration to disk.
    SaveConfig,

    /// Execute multiple effects in sequence.
    Batch(Vec<Effect>),

    /// Load commit history for a repository.
    LoadCommitHistory(PathBuf),

    /// Load diff for a specific commit.
    LoadCommitDiff {
        repo_path: PathBuf,
        commit_hash: String,
    },

    /// Load working directory status.
    LoadWorkingDirStatus(PathBuf),

    /// Stage a file.
    StageFile {
        repo_path: PathBuf,
        file_path: PathBuf,
    },

    /// Unstage a file.
    UnstageFile {
        repo_path: PathBuf,
        file_path: PathBuf,
    },

    /// Stage all changes.
    StageAll(PathBuf),

    /// Unstage all changes.
    UnstageAll(PathBuf),

    /// Create a commit.
    CreateCommit {
        repo_path: PathBuf,
        message: String,
    },

    /// Load author identity.
    LoadAuthorIdentity(PathBuf),

    // ===== 4-Pane Layout Effects =====

    /// Load branch tree.
    LoadBranchTree(PathBuf),

    /// Checkout a branch.
    CheckoutBranch {
        repo_path: PathBuf,
        branch_name: String,
    },

    /// Load file tree.
    LoadFileTree(PathBuf),

    /// Load changed files.
    LoadChangedFiles(PathBuf),

    /// Load file content.
    LoadFileContent {
        repo_path: PathBuf,
        file_path: PathBuf,
    },

    /// Load file diff.
    LoadFileDiff {
        repo_path: PathBuf,
        file_path: PathBuf,
    },
}
